
[functions.get-qbo-accounts]
enabled = true
verify_jwt = true
import_map = "./functions/get-qbo-accounts/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-qbo-accounts/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-qbo-accounts/*.html" ]

[functions.create-qbo-bill]
enabled = true
verify_jwt = true
import_map = "./functions/create-qbo-bill/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-qbo-bill/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-qbo-bill/*.html" ]
